
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 12 20:59:45 GMT 2014
//----------------------------------------------------

package ex2.JCup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 3;
  public static final int INT = 8;
  public static final int DIVIDE = 5;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int ID = 9;
  public static final int error = 1;
  public static final int RPAREN = 7;
  public static final int TIMES = 4;
  public static final int LPAREN = 6;
}

